### ISSUE TITLE
not showing up in appstream.xml.gz 

### ISSUE THREAD

**Issue by maci0** [flathub/org.quetoo.Quetoo#2]
@alexlarsson @TingPing 
maybe I'm doing something wrong.
But Quetoo doesn't show up in the appstream file and therefore not on the application list on flathub.org
also the gnome software center doesn't show the screenshots or the license, license is displayed as unknown.
Is there something wrong with my metadata ?
I couldn't see anything out of the ordinary.
Installing and running the package works fine.

**Comment by TingPing** [comment]
Hmm, missing the `<name>` tag?

**Comment by nedrichards** [comment]
Whatever it is - we might want to consider making sure it's in the required tests for builds in future.

**Comment by maci0** [comment]
added the <name> tag now, build is running lets see if that helps.

**Comment by maci0** [comment]
Ok, added. the update itself did show up in the gnome software center, but still none of the metadata and nothing in appstream.xml.gz

**Comment by maci0** [comment]
Fixed by https://github.com/flathub/org.quetoo.Quetoo/commit/3dce8df5eb910f88ca3180b00e40539e8b994d71
