### ISSUE TITLE
Doesn't seem to have write permission for saving config and taking screenshots.

### ISSUE THREAD

**Issue by iBurley** [flathub/org.quetoo.Quetoo#3]
The game doesn't save my settings on close so I tried to do a `save_config` and it still didn't do anything, screenshots don't save either. I assume it just doesn't have write permissions.

**Comment by iBurley** [comment]
I was wrong, the issue appears to be that it's still expecting to find configs in the home dir instead of within `~/.var/app/org.quetoo.Quetoo`.

**Comment by TingPing** [comment]
This needs to be patched to respect XDG:

https://github.com/jdolan/quetoo/blob/1d823b8733822f9b2f6d0a2d57f60a42a223ef83/src/sys.c#L114-L115

In the mean time we can add `--persist=.quetoo`.
